name: "Translation request"
description: Suggest or work on a new language translation
title: "Help make PlugBrain available to {language} speakers"
labels: ["translation", "good first issue", "help wanted"]

body:
  - type: input
    id: language
    attributes:
      label: Language
      description: Which language do you want to add? (e.g. Spanish, Arabic, Hindi)
      placeholder: "Language"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any notes or tips for this translation? (optional)

  - type: markdown
    attributes:
      value: |
        ### Help make PlugBrain available to {language} speakers:
        
        1. Copy app strings in [strings.xml](https://github.com/msbelaid/PlugBrain/blob/master/app/src/main/res/values/strings.xml) to `res/values-<lang>/strings.xml`.
        2. Translate all the strings in `res/values-<lang>/strings.xml`
        3. Translate the stores metadata (Fastlane files):
          - App description: `fastlane/metadata/android/<lang>/full_description.txt`
          - Short description: `fastlane/metadata/android/<lang>/short_description.txt`
          - Screenshots: `fastlane/metadata/android/<lang>/images/phoneScreenshots/`
